//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMyDB.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iskop
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Sale { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> ID_Mine { get; set; }
    
        public virtual Mine Mine { get; set; }
        public virtual Sale Sale1 { get; set; }
    }
}
