//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMyDB.classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lesuserEntities : DbContext
    {
        private static lesuserEntities _context;

        public static lesuserEntities GetContext()
        {
            if (_context == null)
                _context = new lesuserEntities();
            return _context;
        }
        public lesuserEntities()
            : base("name=lesuserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Iskop> Iskop { get; set; }
        public virtual DbSet<Mine> Mine { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
    }
}
